apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: etechapp
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
